version: "3.9"

services:
  myssh:
    build:
      context: ./ssh
    container_name: ${ssh_name:-mein_container}
    ports:
      - "${ssh_port:-22}:22"
    volumes:
      - "${data_volume}:/data"
    environment:
      - USER=${user}
      - USER_PASSWORD=${user_password}
      - ROOT_PASSWORD=${root_password}
    restart: unless-stopped
    networks:
      - mein_net2

  ub2:
    build:
      context: ./client
    container_name: ${ub_name:-mein_ubuntu2}
    command: sleep infinity
    restart: unless-stopped
    networks:
      - mein_net2

networks:
  mein_net2:
    name: mein_net2